apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-pod
  name: test-pod
  namespace: team-ops
spec:
  containers:
  - image: nginx
    name: test-pod
    resources:
      requests:
        cpu: "100m"   # Uses remaining available CPU requests
        memory: "64Mi"  # Uses remaining available memory requests
      limits:
        cpu: "200m"   # Within the 500m limit
        memory: "128Mi"  # Within the 256Mi limit

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
