apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment
  namespace: team-backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress
        image: polinux/stress
        command: ["stress"]
        args: ["--cpu", "1", "--vm", "1", "--vm-bytes", "1G", "--timeout", "300s"]
