apiVersion: v1
kind: Pod
metadata:
  name: stress-pod
  namespace: team-backup
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args: ["--cpu", "1", "--vm", "1", "--vm-bytes", "1G", "--timeout", "300s"]

