namespaces:
  - name: team-backup
    quota:
      limits:
        cpu: "600m"
        memory: "700Mi"
    limitRange:
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "500m"
        memory: "512Mi"
      max:
        cpu: "2"
        memory: "3Gi"

