namespaces:
  - name: team-prod
    quota:
      limits:
        cpu: "4"
        memory: "6Gi"
    limitRange:
      defaultRequest:
        cpu: "300m"
        memory: "400Mi"
      default:
        cpu: "1000m"
        memory: "1200Mi"
      max:
        cpu: "2"
        memory: "3Gi"

