namespaces:
  - name: team-backup
    quota:
      limits:
        cpu: "1500m"
        memory: "2Gi"
    limitRange:
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "500m"
        memory: "512Mi"
      max:
        cpu: "2"
        memory: "3Gi"

