{{- range .Values.namespaces }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .name }}-quota
  namespace: {{ .name }}
spec:
  hard:
    limits.cpu: {{ .quota.limits.cpu }}
    limits.memory: {{ .quota.limits.memory }}
---
{{- end }}

